import {useMemo,useState} from 'react';
import {Check,ChevronLeft,ChevronRight,Plus,Trash2,X} from 'lucide-react';
import {Button,CheckBox,Field,Guess,Tag} from './Brut';
import {STARTER_CHAPTERS,SUBJECT_ORDER,SUBJECTS} from '../seed';
import {useStore} from '../store';
import {addDays,formatDate,todayISO} from '../dates';
import {derivePhases} from '../phases';
import {buildBacklogDraft,inferPendingTopics,pendingTopicKey} from '../setup-pending';
import {paceBacklog} from '../pacing';
import type {PendingTopic,SubjectId} from '../types';
type Draft={subject:SubjectId;name:string;finished:boolean;key:string};
export function SetupWizard({close}:{close:()=>void}){
  const dates=useStore(s=>s.settings.examDates),setExamDate=useStore(s=>s.setExamDate),pending=useStore(s=>s.pending),chapters=useStore(s=>s.chapters),schoolSync=useStore(s=>s.schoolSync),hardness=useStore(s=>s.settings.hardness),manualOrder=useStore(s=>s.manualOrder),finishSetup=useStore(s=>s.finishSetup),skipSetup=useStore(s=>s.skipSetup);
 const [step,setStep]=useState(0),[rows,setRows]=useState<Draft[]>(()=>{const learned=new Set(chapters.map(c=>pendingTopicKey(c.subject,c.name)));return SUBJECT_ORDER.flatMap(subject=>STARTER_CHAPTERS[subject].map((c,i)=>({subject,name:c.name,finished:c.finished||learned.has(pendingTopicKey(subject,c.name)),key:`${subject}-${i}`})))}),[newName,setNewName]=useState<Record<string,string>>({});
   const [addedPending,setAddedPending]=useState<PendingTopic[]>([]),[removedPendingKeys,setRemovedPendingKeys]=useState<Set<string>>(()=>new Set()),[newPendingName,setNewPendingName]=useState(''),[newPendingSubject,setNewPendingSubject]=useState<SubjectId>('maths'),[pendingNotice,setPendingNotice]=useState('');
 const selected=useMemo(()=>rows.filter(x=>x.finished&&x.name.trim()).map(({subject,name})=>({subject,name})),[rows]);
 const buildPhase=derivePhases(dates)[1],campaignToday=todayISO(),rangeStart=campaignToday>buildPhase.start?campaignToday:buildPhase.start,rangeEnd=buildPhase.end>=rangeStart?buildPhase.end:addDays(rangeStart,14);
   const chapterKeys=useMemo(()=>new Set([...chapters,...selected].map(c=>pendingTopicKey(c.subject,c.name))),[chapters,selected]);
   const inferredPending=useMemo(()=>inferPendingTopics(rows),[rows]);
   const pendingDraft=useMemo(()=>buildBacklogDraft({existing:pending,inferred:inferredPending,added:addedPending,removedKeys:removedPendingKeys,chapterKeys}),[pending,inferredPending,addedPending,removedPendingKeys,chapterKeys]);const pacedDraft=useMemo(()=>paceBacklog(pendingDraft,{today:campaignToday,deadline:dates.preBoards,school:schoolSync,hardness,order:manualOrder}),[pendingDraft,campaignToday,dates.preBoards,schoolSync,hardness,manualOrder]);
 const dateConfig=[['practicals','Practicals'],['preBoards','Pre-boards'],['boards','Boards']] as const;
  const finish=()=>{finishSetup(selected,pendingDraft);close()};
   const addPendingTopic=(event:React.FormEvent)=>{event.preventDefault();const name=newPendingName.trim();if(!name)return;const key=pendingTopicKey(newPendingSubject,name);if(pendingDraft.some(item=>pendingTopicKey(item.subject,item.name)===key)){setPendingNotice('That topic is already in the list.');return}if(removedPendingKeys.has(key)){setRemovedPendingKeys(current=>{const next=new Set(current);next.delete(key);return next});setPendingNotice('Topic added back to the list.')}else{setAddedPending(current=>[...current,{id:`custom-${crypto.randomUUID()}`,subject:newPendingSubject,name}]);setPendingNotice('Topic added.')}setNewPendingName('')};
 return <div className="fixed inset-0 z-50 overflow-y-auto bg-[var(--paper)] p-3 sm:p-8" role="dialog" aria-modal="true" aria-label="First run setup">
  <div className="mx-auto max-w-4xl">
    <header className="flex items-start justify-between"><div><p className="mono text-sm font-bold">BLOCKS / START HERE</p><h1 className="mt-2 text-4xl sm:text-6xl">Make the plan yours.</h1></div><button onClick={()=>{skipSetup();close()}} className="grid h-12 w-12 place-items-center border-[3px] border-[var(--ink)] bg-white" aria-label="Skip setup" data-testid="button-skip-setup"><X strokeWidth={3}/></button></header>
   <div className="my-6 grid grid-cols-3 gap-2">{['DATES','CHAPTERS','BACKLOG'].map((n,i)=><div key={n} className={`brut-sm p-3 ${step===i?'bg-[var(--due)]':'bg-white'}`}><span className="mono text-xs">STEP 0{i+1}</span><div className="display mt-1 text-sm">{n}</div></div>)}</div>
   {step===0&&<section className="space-y-4"><h2 className="text-3xl">These dates are guesses.</h2><p>Change them when school confirms the schedule. Phases move automatically.</p>{dateConfig.map(([key,label])=><div key={key} className="brut-sm grid gap-3 p-4 sm:grid-cols-[1fr_1fr_auto] sm:items-end"><Field label={label}><input type="date" value={dates[key]} onChange={e=>setExamDate(key,e.target.value,dates.confirmed[key])} data-testid={`input-setup-${key}`}/></Field><div className="mono flex items-center gap-2 text-sm">{dates.confirmed[key]?<span className="border-2 border-black bg-[var(--done)] px-2 py-1">CONFIRMED</span>:<Guess/>}<span>{formatDate(dates[key],{day:'numeric',month:'long',year:'numeric'})}</span></div><label className="flex min-h-12 items-center gap-2"><input className="h-6 w-6" type="checkbox" checked={dates.confirmed[key]} onChange={e=>setExamDate(key,dates[key],e.target.checked)} data-testid={`check-confirm-${key}`}/>Confirmed</label></div>)}</section>}
   {step===1&&<section className="space-y-4"><h2 className="text-3xl">What’s already finished?</h2><p className="mono border-2 border-black bg-[var(--biology)] p-3" data-testid="text-chapter-count">{selected.length} {selected.length===1?'chapter':'chapters'} get R1 between {formatDate(rangeStart,{day:'numeric',month:'short'})} and {formatDate(rangeEnd,{day:'numeric',month:'short'})}.</p>{SUBJECT_ORDER.map(subject=><div className="brut-sm p-4" key={subject}><div className="mb-3 flex items-center justify-between"><h3 className="text-2xl">{SUBJECTS[subject].label}</h3><Tag subject={subject}/></div><div className="space-y-2">{rows.filter(x=>x.subject===subject).map(row=><div className="flex items-center gap-3 border-2 border-black bg-white p-2" key={row.key}><CheckBox checked={row.finished} onClick={()=>setRows(rs=>rs.map(x=>x.key===row.key?{...x,finished:!x.finished}:x))} label={`Finished ${row.name}`} testId={`check-setup-${row.key}`}/><input value={row.name} onChange={e=>setRows(rs=>rs.map(x=>x.key===row.key?{...x,name:e.target.value}:x))} aria-label="Chapter name" data-testid={`input-chapter-${row.key}`}/><button className="min-h-12 min-w-12 border-2 border-black" onClick={()=>setRows(rs=>rs.filter(x=>x.key!==row.key))} aria-label={`Delete ${row.name}`} data-testid={`button-delete-${row.key}`}><Trash2 size={18} strokeWidth={3}/></button></div>)}</div><form className="mt-3 flex gap-2" onSubmit={e=>{e.preventDefault();const name=newName[subject]?.trim();if(name){setRows(rs=>[...rs,{subject,name,finished:false,key:crypto.randomUUID()}]);setNewName(v=>({...v,[subject]:''}))}}}><input placeholder={`Add a ${SUBJECTS[subject].label.toLowerCase()} chapter`} value={newName[subject]??''} onChange={e=>setNewName(v=>({...v,[subject]:e.target.value}))} data-testid={`input-add-${subject}`}/><button className="min-h-12 min-w-12 border-[3px] border-black bg-[var(--due)]" aria-label="Add chapter" data-testid={`button-add-${subject}`}><Plus strokeWidth={3}/></button></form></div>)}</section>}
     {step===2&&<section className="space-y-4"><h2 className="text-3xl">Your backlog.</h2><p>Unchecked chapters and extra topics sit here with no dates to plan. BLOCKS paces them toward your pre-boards date automatically — one chapter per subject at a time, so you never juggle two chapters of the same subject. You can nudge any date later from Today.</p><p className="mono border-2 border-black bg-[var(--biology)] p-3" data-testid="text-pending-count">{pendingDraft.length} TOPICS · AUTO-PACED TO {formatDate(dates.preBoards,{day:'numeric',month:'short',year:'numeric'}).toUpperCase()}</p><form className="grid gap-3 sm:grid-cols-[1fr_1.5fr_auto]" onSubmit={addPendingTopic}><Field label="Subject"><select value={newPendingSubject} onChange={e=>setNewPendingSubject(e.target.value as SubjectId)} data-testid="select-add-pending-subject">{SUBJECT_ORDER.map(subject=><option key={subject} value={subject}>{SUBJECTS[subject].label}</option>)}</select></Field><Field label="Topic"><input required value={newPendingName} onChange={e=>setNewPendingName(e.target.value)} placeholder="Add another topic" data-testid="input-add-pending"/></Field><Button type="submit" className="self-end" data-testid="button-add-pending"><Plus strokeWidth={3}/> ADD TOPIC</Button></form>{pendingNotice&&<p className="mono text-sm" role="status" data-testid="text-pending-notice">{pendingNotice}</p>}{pendingDraft.map(item=>{const key=pendingTopicKey(item.subject,item.name);const preview=pacedDraft.find(x=>x.id===item.id);return <div className="brut-sm flex flex-wrap items-center gap-3 p-4" key={item.id} data-testid={`pending-plan-${item.id}`}><div className="min-w-0 flex-1"><Tag subject={item.subject}/><strong className="mt-2 block">{item.name}</strong>{item.id.startsWith('setup-')&&<span className="mono mt-1 inline-block text-xs">FROM UNCHECKED CHAPTER</span>}</div>{preview&&<div className="border-2 border-black bg-[var(--due)] p-3"><span className="mono block text-xs font-bold">LEARN BY</span><strong>{formatDate(preview.due,{day:'numeric',month:'short',year:'numeric'})}</strong><span className="mono mt-1 block text-xs">START {formatDate(preview.plannedStart,{day:'numeric',month:'short'})}</span></div>}<Button variant="danger" onClick={()=>setRemovedPendingKeys(current=>new Set(current).add(key))} aria-label={`Remove ${item.name}`} data-testid={`button-remove-pending-${item.id}`}><Trash2 strokeWidth={3}/> REMOVE</Button></div>})}{pendingDraft.length===0&&<p className="brut-sm p-4" data-testid="empty-pending">Your backlog is empty. Add a topic above, or continue.</p>}</section>}
   <footer className="mt-8 flex flex-wrap justify-between gap-3 border-t-[3px] border-black pt-4">{step>0?<Button variant="ghost" onClick={()=>setStep(s=>s-1)} data-testid="button-setup-back"><ChevronLeft strokeWidth={3}/> BACK</Button>:<span/>}{step<2?<Button onClick={()=>setStep(s=>s+1)} data-testid="button-setup-next">NEXT <ChevronRight strokeWidth={3}/></Button>:<Button onClick={finish} data-testid="button-finish-setup"><Check strokeWidth={3}/> BUILD MY REVISION PLAN</Button>}</footer>
  </div>
 </div>
}