import {useMemo,useState} from 'react';
import {Check,ChevronLeft,ChevronRight,Plus,Trash2,X} from 'lucide-react';
import {Button,CheckBox,Field,Guess,Tag} from './Brut';
import {STARTER_CHAPTERS,SUBJECT_ORDER,SUBJECTS} from '../seed';
import {useStore} from '../store';
import {addDays,formatDate,todayISO} from '../dates';
import {derivePhases} from '../phases';
import type {SubjectId} from '../types';
type Draft={subject:SubjectId;name:string;finished:boolean;key:string};
export function SetupWizard({close}:{close:()=>void}){
  const dates=useStore(s=>s.settings.examDates),setExamDate=useStore(s=>s.setExamDate),pending=useStore(s=>s.pending),setPendingDue=useStore(s=>s.setPendingDue),finishSetup=useStore(s=>s.finishSetup),skipSetup=useStore(s=>s.skipSetup);
 const [step,setStep]=useState(0),[rows,setRows]=useState<Draft[]>(()=>SUBJECT_ORDER.flatMap(subject=>STARTER_CHAPTERS[subject].map((c,i)=>({subject,name:c.name,finished:c.finished,key:`${subject}-${i}`})))),[newName,setNewName]=useState<Record<string,string>>({});
 const selected=useMemo(()=>rows.filter(x=>x.finished&&x.name.trim()).map(({subject,name})=>({subject,name})),[rows]);
 const buildPhase=derivePhases(dates)[1],campaignToday=todayISO(),rangeStart=campaignToday>buildPhase.start?campaignToday:buildPhase.start,rangeEnd=buildPhase.end>=rangeStart?buildPhase.end:addDays(rangeStart,14);
 const dateConfig=[['practicals','Practicals'],['preBoards','Pre-boards'],['boards','Boards']] as const;
 const finish=()=>{finishSetup(selected);close()};
 return <div className="fixed inset-0 z-50 overflow-y-auto bg-[var(--paper)] p-3 sm:p-8" role="dialog" aria-modal="true" aria-label="First run setup">
  <div className="mx-auto max-w-4xl">
    <header className="flex items-start justify-between"><div><p className="mono text-sm font-bold">BLOCKS / START HERE</p><h1 className="mt-2 text-4xl sm:text-6xl">Make the plan yours.</h1></div><button onClick={()=>{skipSetup();close()}} className="grid h-12 w-12 place-items-center border-[3px] border-[var(--ink)] bg-white" aria-label="Skip setup" data-testid="button-skip-setup"><X strokeWidth={3}/></button></header>
   <div className="my-6 grid grid-cols-3 gap-2">{['DATES','CHAPTERS','PENDING'].map((n,i)=><div key={n} className={`brut-sm p-3 ${step===i?'bg-[var(--due)]':'bg-white'}`}><span className="mono text-xs">STEP 0{i+1}</span><div className="display mt-1 text-sm">{n}</div></div>)}</div>
   {step===0&&<section className="space-y-4"><h2 className="text-3xl">These dates are guesses.</h2><p>Change them when school confirms the schedule. Phases move automatically.</p>{dateConfig.map(([key,label])=><div key={key} className="brut-sm grid gap-3 p-4 sm:grid-cols-[1fr_1fr_auto] sm:items-end"><Field label={label}><input type="date" value={dates[key]} onChange={e=>setExamDate(key,e.target.value,dates.confirmed[key])} data-testid={`input-setup-${key}`}/></Field><div className="mono flex items-center gap-2 text-sm">{dates.confirmed[key]?<span className="border-2 border-black bg-[var(--done)] px-2 py-1">CONFIRMED</span>:<Guess/>}<span>{formatDate(dates[key],{day:'numeric',month:'long',year:'numeric'})}</span></div><label className="flex min-h-12 items-center gap-2"><input className="h-6 w-6" type="checkbox" checked={dates.confirmed[key]} onChange={e=>setExamDate(key,dates[key],e.target.checked)} data-testid={`check-confirm-${key}`}/>Confirmed</label></div>)}</section>}
   {step===1&&<section className="space-y-4"><h2 className="text-3xl">What’s already finished?</h2><p className="mono border-2 border-black bg-[var(--biology)] p-3" data-testid="text-chapter-count">{selected.length} {selected.length===1?'chapter':'chapters'} get R1 between {formatDate(rangeStart,{day:'numeric',month:'short'})} and {formatDate(rangeEnd,{day:'numeric',month:'short'})}.</p>{SUBJECT_ORDER.map(subject=><div className="brut-sm p-4" key={subject}><div className="mb-3 flex items-center justify-between"><h3 className="text-2xl">{SUBJECTS[subject].label}</h3><Tag subject={subject}/></div><div className="space-y-2">{rows.filter(x=>x.subject===subject).map(row=><div className="flex items-center gap-3 border-2 border-black bg-white p-2" key={row.key}><CheckBox checked={row.finished} onClick={()=>setRows(rs=>rs.map(x=>x.key===row.key?{...x,finished:!x.finished}:x))} label={`Finished ${row.name}`} testId={`check-setup-${row.key}`}/><input value={row.name} onChange={e=>setRows(rs=>rs.map(x=>x.key===row.key?{...x,name:e.target.value}:x))} aria-label="Chapter name" data-testid={`input-chapter-${row.key}`}/><button className="min-h-12 min-w-12 border-2 border-black" onClick={()=>setRows(rs=>rs.filter(x=>x.key!==row.key))} aria-label={`Delete ${row.name}`} data-testid={`button-delete-${row.key}`}><Trash2 size={18} strokeWidth={3}/></button></div>)}</div><form className="mt-3 flex gap-2" onSubmit={e=>{e.preventDefault();const name=newName[subject]?.trim();if(name){setRows(rs=>[...rs,{subject,name,finished:false,key:crypto.randomUUID()}]);setNewName(v=>({...v,[subject]:''}))}}}><input placeholder={`Add a ${SUBJECTS[subject].label.toLowerCase()} chapter`} value={newName[subject]??''} onChange={e=>setNewName(v=>({...v,[subject]:e.target.value}))} data-testid={`input-add-${subject}`}/><button className="min-h-12 min-w-12 border-[3px] border-black bg-[var(--due)]" aria-label="Add chapter" data-testid={`button-add-${subject}`}><Plus strokeWidth={3}/></button></form></div>)}</section>}
   {step===2&&<section className="space-y-4"><h2 className="text-3xl">A few topics still to learn.</h2><p>Deadlines are editable. Once learned, each topic joins the revision queue.</p>{pending.filter(x=>!x.doneOn).map(item=><div className="brut-sm flex flex-wrap items-center gap-3 p-4" key={item.id}><Tag subject={item.subject}/><strong className="min-w-48 flex-1">{item.name}</strong><Field label="Deadline"><input type="date" value={item.due} onChange={e=>setPendingDue(item.id,e.target.value)} data-testid={`input-pending-date-${item.id}`}/></Field></div>)}{!pending.length&&<p className="brut-sm p-4">No pending topics. You can add them later in Chapters.</p>}</section>}
   <footer className="mt-8 flex flex-wrap justify-between gap-3 border-t-[3px] border-black pt-4">{step>0?<Button variant="ghost" onClick={()=>setStep(s=>s-1)} data-testid="button-setup-back"><ChevronLeft strokeWidth={3}/> BACK</Button>:<span/>}{step<2?<Button onClick={()=>setStep(s=>s+1)} data-testid="button-setup-next">NEXT <ChevronRight strokeWidth={3}/></Button>:<Button onClick={finish} data-testid="button-finish-setup"><Check strokeWidth={3}/> BUILD MY REVISION PLAN</Button>}</footer>
  </div>
 </div>
}