import {useMemo,useState} from 'react';
import {ChevronDown,ChevronUp,Plus,Trash2} from 'lucide-react';
import {Button,CheckBox,Field,Segments,Tag} from '../components/Brut';
import {RevisionCheckIn} from '../components/RevisionCheckIn';
import {useStore} from '../store';
import {formatDate,revStatus,todayISO} from '../dates';
import {SUBJECT_ORDER,SUBJECTS} from '../seed';
import type {SubjectId} from '../types';
export function ChaptersPage({openSetup}:{openSetup:()=>void}){
 const s=useStore(),[subject,setSubject]=useState<SubjectId|'all'>('all'),[name,setName]=useState(''),[newSubject,setNewSubject]=useState<SubjectId>('maths'),[learned,setLearned]=useState(todayISO()),[bulk,setBulk]=useState(''),[bulkSubject,setBulkSubject]=useState<SubjectId>('maths'),[bulkDate,setBulkDate]=useState(todayISO()),[expanded,setExpanded]=useState<string|null>(null);
 const list=useMemo(()=>s.chapters.filter(c=>subject==='all'||c.subject===subject).sort((a,b)=>SUBJECT_ORDER.indexOf(a.subject)-SUBJECT_ORDER.indexOf(b.subject)||a.name.localeCompare(b.name)),[s.chapters,subject]);
 const submit=(e:React.FormEvent)=>{e.preventDefault();s.addChapter(newSubject,name,learned);setName('')};
 const submitBulk=(e:React.FormEvent)=>{e.preventDefault();bulk.split(/\r?\n/).map(x=>x.trim()).filter(Boolean).forEach(x=>s.addChapter(bulkSubject,x,bulkDate));setBulk('')};
 return <main className="mx-auto max-w-5xl space-y-5 px-4 pb-32 pt-6 sm:px-8"><header className="flex flex-wrap items-end justify-between gap-3"><div><p className="mono text-xs font-bold">LIBRARY / SPACED REVISION</p><h1 className="mt-2 text-5xl sm:text-6xl">Chapters.</h1><p className="mt-2">Finish a chapter. The next three revision dates are handled.</p></div>{!s.setupDone&&<Button onClick={openSetup} data-testid="button-finish-setup-chapters">FINISH SETUP</Button>}</header>
  <div className="flex flex-wrap gap-2" aria-label="Filter chapters">{(['all',...SUBJECT_ORDER] as const).map(id=><button className={`brut-btn ${subject===id?'':'bg-white'}`} style={id==='all'?{}:subject===id?{background:SUBJECTS[id].color}:undefined} key={id} onClick={()=>setSubject(id)} data-testid={`filter-chapters-${id}`}>{id==='all'?'ALL':SUBJECTS[id].label}</button>)}</div>
  <section className="brut p-4"><h2 className="text-2xl">Add a chapter.</h2><form onSubmit={submit} className="mt-3 grid gap-3 md:grid-cols-[1.5fr_1fr_1fr_auto] md:items-end"><Field label="Chapter name"><input required value={name} onChange={e=>setName(e.target.value)} placeholder="e.g. Definite Integrals" data-testid="input-chapter-name"/></Field><Field label="Subject"><select value={newSubject} onChange={e=>setNewSubject(e.target.value as SubjectId)} data-testid="select-chapter-subject">{SUBJECT_ORDER.map(id=><option value={id} key={id}>{SUBJECTS[id].label}</option>)}</select></Field><Field label="Learned on"><input type="date" value={learned} onChange={e=>setLearned(e.target.value)} data-testid="input-chapter-learned"/></Field><Button type="submit" data-testid="button-add-chapter"><Plus size={18} strokeWidth={3}/> ADD</Button></form></section>
  <details className="brut-sm bg-white p-4"><summary className="display cursor-pointer text-lg">BULK ADD CHAPTERS</summary><p className="mt-2">One chapter name per line. Every line gets a revision schedule.</p><form onSubmit={submitBulk} className="mt-3 grid gap-3 sm:grid-cols-3"><Field label="Subject"><select value={bulkSubject} onChange={e=>setBulkSubject(e.target.value as SubjectId)} data-testid="select-bulk-subject">{SUBJECT_ORDER.map(id=><option key={id} value={id}>{SUBJECTS[id].label}</option>)}</select></Field><Field label="Learned on"><input type="date" value={bulkDate} onChange={e=>setBulkDate(e.target.value)} data-testid="input-bulk-date"/></Field><Field label="Chapter names"><textarea rows={3} value={bulk} onChange={e=>setBulk(e.target.value)} placeholder={'Chapter one\nChapter two'} data-testid="input-bulk-chapters"/></Field><Button type="submit" className="sm:col-span-3" data-testid="button-bulk-add">ADD ALL LINES</Button></form></details>
  <section className="space-y-3"><div className="flex items-baseline justify-between"><h2 className="text-3xl">Your chapters</h2><span className="mono text-xs">{list.length} TOTAL</span></div>{list.length===0?<div className="brut-sm bg-[var(--biology)] p-6" data-testid="empty-chapters"><h3 className="text-xl">No chapters here yet.</h3><p>Add one above. Its R1, R2 and R3 dates will appear automatically.</p></div>:list.map(ch=>{const open=expanded===ch.id;return <article className="brut overflow-hidden" key={ch.id} data-testid={`chapter-${ch.id}`}><button className="flex min-h-[76px] w-full items-center gap-3 p-3 text-left sm:p-4" onClick={()=>setExpanded(open?null:ch.id)} aria-expanded={open} data-testid={`button-expand-${ch.id}`}><Tag subject={ch.subject}/><div className="min-w-0 flex-1"><strong className="block">{ch.name}</strong><span className="mono text-xs">LEARNED {formatDate(ch.learnedOn)}</span></div><div className="hidden w-28 sm:block"><Segments total={3} filled={ch.revisions.filter(r=>r.doneOn).length} color={SUBJECTS[ch.subject].color}/></div>{open?<ChevronUp strokeWidth={3}/>:<ChevronDown strokeWidth={3}/>}</button>
  <div className="flex flex-wrap items-center gap-3 border-t-[3px] border-black bg-[#fffdf7] px-4 py-3"><span className="mono text-xs font-bold">PYQ DONE</span><CheckBox checked={ch.pyqDone} onClick={()=>s.togglePyq(ch.id)} label={`${ch.name} PYQ done`} testId={`check-pyq-${ch.id}`}/><div className="flex-1"/><button className="brut-btn bg-white text-xs" onClick={()=>{if(window.confirm(`Delete ${ch.name} and its revision schedule?`))s.deleteChapter(ch.id)}} data-testid={`button-delete-chapter-${ch.id}`}><Trash2 size={16} strokeWidth={3}/> DELETE</button></div>
   {open&&<div className="space-y-3 border-t-[3px] border-black p-4"><div className="grid gap-3 sm:grid-cols-2"><Field label="Chapter name"><input value={ch.name} onChange={e=>s.editChapter(ch.id,{name:e.target.value})} data-testid={`input-edit-chapter-${ch.id}`}/></Field><Field label="Learned on"><input type="date" value={ch.learnedOn} onChange={e=>s.editChapter(ch.id,{learnedOn:e.target.value})} data-testid={`input-edit-learned-${ch.id}`}/></Field></div><div className="grid gap-2 sm:grid-cols-3">{ch.revisions.map(rev=>{const status=revStatus(rev,todayISO());return <div className="brut-sm flex flex-col gap-3 p-3" key={rev.pass}><div className="min-w-0 flex-1"><span className={`mono border-2 border-black px-2 py-1 text-xs font-bold ${status==='overdue'?'bg-[var(--overdue)] text-white':status==='due'?'bg-[var(--due)]':status==='done'?'bg-[var(--done)]':'bg-white'}`}>{rev.pass} · {status.toUpperCase()}</span><p className="mono mt-2 text-xs">{formatDate(rev.dueOn,{day:'numeric',month:'short',year:'numeric'})}</p>{rev.lastResult&&<p className="mono mt-1 text-xs">LAST RECALL: {rev.lastResult.toUpperCase()}</p>}</div>{!rev.doneOn&&<RevisionCheckIn chapterName={ch.name} pass={rev.pass} testId={`check-chapter-revision-${ch.id}-${rev.pass}`} onRate={result=>s.completeRevision(ch.id,rev.pass,result)}/>}</div>})}</div></div>}
 </article>})}</section>
 </main>
}