import {useMemo,useState} from 'react';
import {Trash2} from 'lucide-react';
import {Button,CheckBox,Field,Tag} from '../components/Brut';
import {useStore} from '../store';
import {addDays,formatDate,todayISO} from '../dates';
import {SUBJECT_ORDER,SUBJECTS} from '../seed';
import type {ErrorReason,SubjectId} from '../types';
const REASONS:ErrorReason[]=['concept','calculation','silly','time'];
const reasonLabel:Record<ErrorReason,string>={concept:'Concept',calculation:'Calculation',silly:'Silly mistake',time:'Time'};
export function ErrorsPage(){
 const s=useStore(),[subject,setSubject]=useState<SubjectId|'all'>('all'),[reason,setReason]=useState<ErrorReason|'all'>('all'),[date,setDate]=useState(todayISO()),[formSubject,setFormSubject]=useState<SubjectId>('maths'),[topic,setTopic]=useState(''),[formReason,setFormReason]=useState<ErrorReason>('concept'),[fix,setFix]=useState('');
 const rows=useMemo(()=>s.errors.filter(e=>(subject==='all'||e.subject===subject)&&(reason==='all'||e.reason===reason)).sort((a,b)=>b.date.localeCompare(a.date)),[s.errors,subject,reason]);
 const counts=REASONS.map(r=>({reason:r,count:s.errors.filter(e=>e.reason===r).length}));
 const submit=(e:React.FormEvent)=>{e.preventDefault();s.addError({subject:formSubject,topic,reason:formReason,fix,date});setTopic('');setFix('')};
 return <main className="mx-auto max-w-5xl space-y-5 px-4 pb-32 pt-6 sm:px-8"><header><p className="mono text-xs font-bold">LOG IT · FIX IT · REDO IT</p><h1 className="mt-2 text-5xl sm:text-6xl">Errors.</h1><p className="mt-2">Every mistake gets a redo date. No hiding the useful stuff.</p></header>
  <section className="brut p-4"><div className="flex flex-wrap items-baseline justify-between gap-2"><h2 className="text-2xl">What’s costing marks?</h2><span className="mono text-xs">{s.errors.length} LOGGED</span></div><div className="mt-4 grid grid-cols-2 gap-2 sm:grid-cols-4">{counts.map(x=><article className="brut-sm p-3" key={x.reason} data-testid={`error-summary-${x.reason}`}><p className="mono text-xs">{reasonLabel[x.reason].toUpperCase()}</p><p className="display mt-1 text-3xl">{x.count}</p><div className="mt-2 flex gap-1">{Array.from({length:Math.min(Math.max(s.errors.length,1),8)},(_,i)=><i key={i} className="h-3 flex-1 border-2 border-black" style={{background:i<x.count?'var(--maths)':'white'}}/>)}</div></article>)}</div></section>
  <section className="brut p-4"><h2 className="text-3xl">Add an error.</h2><form onSubmit={submit} className="mt-3 grid gap-3 sm:grid-cols-2"><Field label="Date"><input type="date" value={date} onChange={e=>setDate(e.target.value)} data-testid="input-error-date"/></Field><Field label="Subject"><select value={formSubject} onChange={e=>setFormSubject(e.target.value as SubjectId)} data-testid="select-error-subject">{SUBJECT_ORDER.map(x=><option value={x} key={x}>{SUBJECTS[x].label}</option>)}</select></Field><Field label="Question or topic"><input required value={topic} onChange={e=>setTopic(e.target.value)} placeholder="What went wrong?" data-testid="input-error-topic"/></Field><Field label="Reason"><select value={formReason} onChange={e=>setFormReason(e.target.value as ErrorReason)} data-testid="select-error-reason">{REASONS.map(x=><option value={x} key={x}>{reasonLabel[x]}</option>)}</select></Field><Field label="One-line fix"><input required value={fix} onChange={e=>setFix(e.target.value)} placeholder="What will you do differently?" data-testid="input-error-fix"/></Field><div className="flex items-end"><Button type="submit" className="w-full" data-testid="button-add-error">LOG ERROR · REDO {formatDate(addDays(date,7))}</Button></div></form></section>
  <section className="space-y-3"><div className="flex flex-wrap items-end justify-between gap-3"><h2 className="text-3xl">Error log</h2><span className="mono text-xs">{rows.length} SHOWING</span></div><div className="grid gap-2 sm:grid-cols-2"><Field label="Subject filter"><select value={subject} onChange={e=>setSubject(e.target.value as SubjectId|'all')} data-testid="filter-errors-subject"><option value="all">All subjects</option>{SUBJECT_ORDER.map(x=><option value={x} key={x}>{SUBJECTS[x].label}</option>)}</select></Field><Field label="Reason filter"><select value={reason} onChange={e=>setReason(e.target.value as ErrorReason|'all')} data-testid="filter-errors-reason"><option value="all">All reasons</option>{REASONS.map(x=><option value={x} key={x}>{reasonLabel[x]}</option>)}</select></Field></div>
   {!rows.length?<div className="brut-sm bg-[var(--biology)] p-6" data-testid="empty-errors"><h3 className="text-2xl">No errors logged.</h3><p>When one costs you a mark, log the fix. Redo it a week later.</p></div>:rows.map(e=>{const due=!e.redoneOn&&e.redoOn<=todayISO();return <article className="brut flex flex-wrap items-start gap-3 p-4" key={e.id} data-testid={`error-${e.id}`}><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><Tag subject={e.subject}/><span className="mono border-2 border-black bg-white px-2 py-1 text-xs">{reasonLabel[e.reason].toUpperCase()}</span>{due&&<span className="mono border-2 border-black bg-[var(--due)] px-2 py-1 text-xs font-bold">REDO</span>}</div><h3 className="mt-2 text-xl">{e.topic}</h3><p className="mt-1 font-bold">Fix: {e.fix}</p><p className="mono mt-2 text-xs">LOGGED {formatDate(e.date)} · REDO {formatDate(e.redoOn)}{e.redoneOn?` · DONE ${formatDate(e.redoneOn)}`:''}</p></div>{due&&!e.redoneOn&&<CheckBox checked={false} onClick={()=>s.redoError(e.id)} label={`Mark redo complete for ${e.topic}`} testId={`check-redo-${e.id}`}/>}<Button variant="danger" onClick={()=>{if(window.confirm('Delete this error entry?'))s.deleteError(e.id)}} data-testid={`button-delete-error-${e.id}`}><Trash2 size={18}/> DELETE</Button></article>})}</section>
 </main>
}