import {useMemo,useState} from 'react';
import {Plus,Trash2} from 'lucide-react';
import {Button,CheckBox,Field,Guess,Segments,Tag} from '../components/Brut';
import {useStore} from '../store';
import {addDays,daysBetween,formatDate,mondayOf,todayISO} from '../dates';
import {DEFAULT_EXAM_DATES,derivePhases} from '../phases';
import {BLOCK_TIMES,SUBJECT_ORDER,SUBJECTS,SUBJECT_WEIGHT,WEEK_MILESTONES,WEEK_TEMPLATE} from '../seed';
import type {SubjectId} from '../types';

type PlanTab='overview'|'practicals'|'papers';
const BASE_PHASES=derivePhases(DEFAULT_EXAM_DATES);
export function PlanPage(){
 const s=useStore(),[tab,setTab]=useState<PlanTab>('overview'),today=todayISO(),phases=derivePhases(s.settings.examDates),[expanded,setExpanded]=useState<number|null>(null);
 const [mockSubject,setMockSubject]=useState<SubjectId>('physics'),[mockDate,setMockDate]=useState(today),[mockNotes,setMockNotes]=useState(''),[mockObtained,setMockObtained]=useState(''),[mockTotal,setMockTotal]=useState(''),[practicalText,setPracticalText]=useState(''),[paperSubject,setPaperSubject]=useState<SubjectId>('maths'),[paper,setPaper]=useState<'language'|'literature'>('language'),[paperDate,setPaperDate]=useState(today),[paperTime,setPaperTime]=useState('');
  const milestones=useMemo(()=>WEEK_MILESTONES.map(w=>{const phaseIndex=w.week<=3?1:w.week<=6?2:3,shift=daysBetween(BASE_PHASES[phaseIndex].start,phases[phaseIndex].start);return{...w,start:addDays(w.start,shift),end:addDays(w.end,shift)}}).sort((a,b)=>Number(today>=b.start&&today<=b.end)-Number(today>=a.start&&today<=a.end)||a.week-b.week),[phases,today]);
 const currentWeek=milestones.find(w=>today>=w.start&&today<=w.end)?.week;
 const hasDateGuesses=Object.values(s.settings.examDates.confirmed).some(confirmed=>!confirmed);
 const checklist=(subject:SubjectId)=>s.practicalItems.filter(x=>x.subject===subject),dueFiles=addDays(s.settings.examDates.practicals,-7);
 const submitMock=(e:React.FormEvent)=>{e.preventDefault();const obtained=mockObtained?Number(mockObtained):undefined,total=mockTotal?Number(mockTotal):undefined;s.addMock({subject:mockSubject,date:mockDate,notes:mockNotes,...(obtained!==undefined&&total?{obtained,total}:{})});if(obtained!==undefined&&total)s.addScore({subject:mockSubject,date:mockDate,label:`Practical mock · ${SUBJECTS[mockSubject].label}`,type:'practical-mock',obtained,total,note:mockNotes});setMockNotes('');setMockObtained('');setMockTotal('')};
 const submitPaper=(e:React.FormEvent)=>{e.preventDefault();s.addPaper({subject:paperSubject,date:paperDate,...(paperSubject==='english'?{paper}:{}),...(paperTime?{time:paperTime}:{})});setPaperTime('')};
 return <main className="mx-auto max-w-5xl space-y-5 px-4 pb-32 pt-6 sm:px-8"><header><p className="mono text-xs font-bold">YOUR ROUTE TO EXAMS</p><h1 className="mt-2 text-5xl sm:text-6xl">Plan.</h1></header>
  <nav className="grid grid-cols-3 gap-2" aria-label="Plan sections">{([['overview','OVERVIEW'],['practicals','PRACTICALS'],['papers','PAPERS']] as const).map(([id,label])=><button className={`brut-btn ${tab===id?'':'bg-white'}`} key={id} onClick={()=>setTab(id)} aria-pressed={tab===id} data-testid={`tab-plan-${id}`}>{label}</button>)}</nav>
  {tab==='overview'&&<><section className="space-y-3"><h2 className="text-3xl">The phases.</h2>{phases.map(p=>{const active=today>=p.start&&today<=p.end;return <article key={p.id} className="brut flex gap-4 p-4" style={{background:active?'var(--due)':'white'}} data-testid={`phase-${p.id}`}><span className="display text-4xl">{String(p.id).padStart(2,'0')}</span><div className="flex-1"><div className="flex flex-wrap items-center gap-2"><h3 className="text-2xl">{p.name}</h3>{active&&<span className="mono border-2 border-black bg-white px-2 py-1 text-xs">NOW</span>}</div><p className="mono mt-1 flex flex-wrap items-center gap-2 text-xs">{formatDate(p.start,{day:'numeric',month:'short',year:'numeric'})} — {formatDate(p.end,{day:'numeric',month:'short',year:'numeric'})} {hasDateGuesses&&<Guess/>}</p><p className="mt-2">{p.job}</p>{p.squeezed&&<p className="mt-2 font-bold">This phase is squeezed by the current practical date.</p>}</div></article>})}</section>
  <section className="space-y-3"><div className="flex flex-wrap items-end justify-between gap-2"><h2 className="text-3xl">Week checkpoints.</h2><p className="mono text-xs">TICK AS YOU GO</p></div>{milestones.map(w=>{const active=w.week===currentWeek,open=expanded===w.week||(expanded===null&&active);return <article key={w.week} className="brut overflow-hidden" data-testid={`milestone-week-${w.week}`}><button className="flex min-h-16 w-full items-center gap-3 p-4 text-left" style={{background:active?'var(--due)':'white'}} onClick={()=>setExpanded(open?null:w.week)} aria-expanded={open} data-testid={`button-week-${w.week}`}><span className="mono text-xs font-bold">WEEK {String(w.week).padStart(2,'0')}</span><strong className="flex-1">{formatDate(w.start)} — {formatDate(w.end)} {hasDateGuesses&&<Guess/>}</strong><span className="mono text-xs">{w.items.filter((_,i)=>s.milestonesDone[`${w.week}:${i}`]).length}/{w.items.length}</span></button>{open&&<div className="space-y-2 border-t-[3px] border-black p-3">{w.items.map((item,i)=><div className={`flex min-h-14 items-center gap-3 border-2 border-black p-2 ${s.milestonesDone[`${w.week}:${i}`]?'bg-[#E9FFF6]':'bg-white'}`} key={`${w.week}-${i}`}><CheckBox checked={!!s.milestonesDone[`${w.week}:${i}`]} onClick={()=>s.toggleMilestone(`${w.week}:${i}`)} label={item} testId={`check-milestone-${w.week}-${i}`}/><p className="font-bold">{item.replace(/Sun Oct 25/i,'Sunday checkpoint').replace(/Sun Nov 1/i,'Sunday checkpoint').replace(/Nov 8/i,formatDate(dueFiles)).replace(/Nov 30/i,formatDate(addDays(s.settings.examDates.preBoards,-1)))}</p></div>)}</div>}</article>})}</section>
  <section className="brut p-4"><h2 className="text-3xl">Time leans.</h2><p className="mt-2">Maths and Physics get the biggest share. The rest stay warm.</p><div className="mt-3 grid gap-3 sm:grid-cols-2">{SUBJECT_ORDER.map(subject=>{const share=SUBJECT_WEIGHT[subject]/Object.values(SUBJECT_WEIGHT).reduce((sum,v)=>sum+v,0),segments=Math.round(share*20);return <div className="brut-sm flex items-center gap-3 p-3" key={subject} data-testid={`time-share-${subject}`}><Tag subject={subject}/><div className="flex-1"><Segments total={20} filled={segments} color={SUBJECTS[subject].color}/></div><span className="mono text-xs">{Math.round(share*100)}%</span></div>})}</div></section>
  <section className="brut p-4"><h2 className="text-3xl">Weekly template.</h2><p className="mt-2">A flexible default, not a rulebook. Move blocks when life happens.</p><div className="mt-4 grid gap-3 md:grid-cols-2">{[1,2,3,4,5,6,0].map(day=><article className="brut-sm p-3" key={day}><h3 className="display text-xl">{['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'][day]}</h3><div className="mt-2 space-y-2">{(['A','B','C'] as const).map(b=>{const plan=WEEK_TEMPLATE[day][b];const sub=plan.subject in SUBJECTS?plan.subject as SubjectId:undefined;return <div className="flex items-start gap-2 border-2 border-black bg-white p-2" key={b}><span className="mono border-2 border-black bg-[var(--due)] px-2">{b}</span><div className="flex-1">{sub?<Tag subject={sub}/>:<b className="mono text-xs">{String(plan.subject).toUpperCase()}</b>}<p className="mt-1 font-bold">{plan.focus}</p><small className="mono">{BLOCK_TIMES[b].length}</small></div></div>})}</div></article>)}</div></section></>}
  {tab==='practicals'&&<><section className="brut flex flex-wrap items-center justify-between gap-3 p-4" data-testid="practical-countdown"><div><p className="mono text-xs font-bold">PRACTICAL EXAMS</p><p className="display mt-1 text-4xl">{Math.max(0,daysBetween(today,s.settings.examDates.practicals))} DAYS</p><p className="mono mt-1">{formatDate(s.settings.examDates.practicals,{day:'numeric',month:'long',year:'numeric'})} {!s.settings.examDates.confirmed.practicals&&<Guess/>}</p></div><div className="border-l-[3px] border-black pl-4"><p className="font-bold">Files done by {formatDate(dueFiles,{day:'numeric',month:'short'})} {!s.settings.examDates.confirmed.practicals&&<Guess/>}.</p><p>Mock practical every Saturday in Phase 2.</p></div></section>
  <section className="grid gap-4 md:grid-cols-2">{SUBJECT_ORDER.filter(x=>x!=='english').map(subject=>{const items=checklist(subject),complete=items.filter(x=>s.practicalChecks[x.id]).length;return <article className="brut p-4" key={subject}><div className="flex items-center justify-between gap-2"><h2 className="text-2xl">{SUBJECTS[subject].label}</h2><Tag subject={subject}/></div><div className="my-3"><Segments total={Math.max(items.length,1)} filled={complete} color={SUBJECTS[subject].color} testId={`progress-practical-${subject}`}/><p className="mono mt-1 text-xs">{complete}/{items.length} DONE</p></div><div className="space-y-2">{items.map(item=><div className="flex items-center gap-2 border-2 border-black bg-white p-2" key={item.id}><CheckBox checked={!!s.practicalChecks[item.id]} onClick={()=>s.togglePractical(item.id)} label={item.text} testId={`check-practical-${item.id}`}/><input value={item.text} onChange={e=>s.editPractical(item.id,e.target.value)} aria-label={`Edit ${item.text}`} data-testid={`input-practical-${item.id}`}/><button className="min-h-12 min-w-12 border-2 border-black" onClick={()=>s.deletePractical(item.id)} aria-label={`Delete practical item`} data-testid={`button-delete-practical-${item.id}`}><Trash2 size={17} strokeWidth={3}/></button></div>)}</div><form className="mt-3 flex gap-2" onSubmit={e=>{e.preventDefault();s.addPractical(subject,practicalText);setPracticalText('')}}><input value={practicalText} onChange={e=>setPracticalText(e.target.value)} placeholder="Add checklist item" data-testid={`input-add-practical-${subject}`}/><button className="min-h-12 min-w-12 border-[3px] border-black bg-[var(--due)]" aria-label="Add checklist item" data-testid={`button-add-practical-${subject}`}><Plus strokeWidth={3}/></button></form></article>})}</section>
  <section className="brut p-4"><h2 className="text-3xl">Mock practical log.</h2><form className="mt-3 grid gap-3 sm:grid-cols-2" onSubmit={submitMock}><Field label="Date"><input type="date" value={mockDate} onChange={e=>setMockDate(e.target.value)} data-testid="input-mock-date"/></Field><Field label="Subject"><select value={mockSubject} onChange={e=>setMockSubject(e.target.value as SubjectId)} data-testid="select-mock-subject">{SUBJECT_ORDER.filter(x=>x!=='english').map(x=><option key={x} value={x}>{SUBJECTS[x].label}</option>)}</select></Field><Field label="Notes"><input value={mockNotes} onChange={e=>setMockNotes(e.target.value)} placeholder="What needs another run?" data-testid="input-mock-notes"/></Field><div className="grid grid-cols-2 gap-2"><Field label="Marks (optional)"><input type="number" min="0" value={mockObtained} onChange={e=>setMockObtained(e.target.value)} data-testid="input-mock-obtained"/></Field><Field label="Out of"><input type="number" min="1" value={mockTotal} onChange={e=>setMockTotal(e.target.value)} data-testid="input-mock-total"/></Field></div><Button type="submit" className="sm:col-span-2" data-testid="button-save-mock">LOG MOCK</Button></form>{s.mockPracticals.map(m=><div className="brut-sm mt-3 flex items-center justify-between gap-3 p-3" key={m.id} data-testid={`mock-${m.id}`}><div><b>{SUBJECTS[m.subject].label}</b><p className="mono text-xs">{formatDate(m.date,{day:'numeric',month:'short',year:'numeric'})} {m.obtained!==undefined?`· ${m.obtained}/${m.total}`:''}</p><p>{m.notes}</p></div><button className="brut-btn bg-white" onClick={()=>s.deleteMock(m.id)} data-testid={`button-delete-mock-${m.id}`}><Trash2 size={17}/></button></div>)}</section></>}
  {tab==='papers'&&<><section className="brut p-4"><h2 className="text-3xl">Paper timetable.</h2><p className="mt-2">Add each paper when school releases the timetable. Today will switch to next-paper mode automatically.</p><form className="mt-4 grid gap-3 sm:grid-cols-2" onSubmit={submitPaper}><Field label="Subject"><select value={paperSubject} onChange={e=>setPaperSubject(e.target.value as SubjectId)} data-testid="select-paper-subject">{SUBJECT_ORDER.map(x=><option key={x} value={x}>{SUBJECTS[x].label}</option>)}</select></Field>{paperSubject==='english'&&<Field label="Paper"><select value={paper} onChange={e=>setPaper(e.target.value as typeof paper)} data-testid="select-paper-english"><option value="language">English 1 · Language</option><option value="literature">English 2 · Literature</option></select></Field>}<Field label="Date"><input type="date" value={paperDate} onChange={e=>setPaperDate(e.target.value)} data-testid="input-paper-date"/></Field><Field label="Time (optional)"><input type="time" value={paperTime} onChange={e=>setPaperTime(e.target.value)} data-testid="input-paper-time"/></Field><Button className="sm:col-span-2" type="submit" data-testid="button-add-paper"><Plus size={18}/> ADD PAPER</Button></form></section>
   {!s.papers.length?<div className="brut-sm bg-[var(--biology)] p-6" data-testid="empty-papers"><h3 className="text-2xl">No timetable yet.</h3><p>Add it when school releases it.</p></div>:<section className="space-y-3"><h2 className="text-3xl">Exam order.</h2>{s.papers.map((p,i)=><article className="brut flex flex-wrap items-center gap-3 p-4" key={p.id} data-testid={`paper-${p.id}`}><span className="display text-3xl">{String(i+1).padStart(2,'0')}</span><Tag subject={p.subject}/><div className="flex-1"><h3 className="text-xl">{SUBJECTS[p.subject].label}{p.paper?` · ${p.paper}`:''}</h3><p className="mono text-sm">{formatDate(p.date,{weekday:'long',day:'numeric',month:'long',year:'numeric'})}{p.time?` · ${p.time}`:''}</p></div><span className="mono border-2 border-black bg-[var(--due)] px-2 py-1 text-sm">{daysBetween(today,p.date)<=0?'TODAY':`${daysBetween(today,p.date)} DAYS`}</span><Button variant="danger" onClick={()=>s.removePaper(p.id)} data-testid={`button-remove-paper-${p.id}`}><Trash2 size={18}/> REMOVE</Button></article>)}</section>}</>}
 </main>
}