import {useEffect,useMemo,useState} from 'react';
import {ArrowDown,ArrowRight,ArrowUp,Trash2} from 'lucide-react';
import {Button,Field,Segments,Tag} from '../components/Brut';
import {useStore} from '../store';
import {formatDate,getDueItems,mondayOf,todayISO} from '../dates';
import {HALF_YEARLY_NOTES,SUBJECT_ORDER,SUBJECTS} from '../seed';
import {pct,scoreTarget,subjectTrend} from '../marks';
import type {ErrorReason,ScoreType,SubjectId} from '../types';
type Tab='weekly'|'marks';
export function ReviewPage(){
 const s=useStore(),[tab,setTab]=useState<Tab>('weekly'),today=todayISO(),weekStart=mondayOf(today),stored=s.reviews.find(r=>r.weekStart===weekStart);
 const [hit,setHit]=useState(false),[mainReason,setMainReason]=useState<ErrorReason>('concept'),[top,setTop]=useState<[string,string,string]>(['','','']),[showOverdue,setShowOverdue]=useState(false);
 const [scoreSubject,setScoreSubject]=useState<SubjectId>('maths'),[scorePaper,setScorePaper]=useState<'language'|'literature'>('language'),[scoreType,setScoreType]=useState<ScoreType>('chapter-test'),[scoreDate,setScoreDate]=useState(today),[scoreLabel,setScoreLabel]=useState(''),[obtained,setObtained]=useState(''),[total,setTotal]=useState('100'),[note,setNote]=useState('');
 const due=getDueItems(s.chapters,today).filter(x=>x.status==='overdue'),primarySubjects:SubjectId[]=['maths','physics','chemistry','biology','english'];
 const weeklyErrors=s.errors.filter(e=>e.date>=weekStart&&e.date<=today),commonError=weeklyErrors.sort((a,b)=>weeklyErrors.filter(x=>x.reason===b.reason).length-weeklyErrors.filter(x=>x.reason===a.reason).length)[0]?.reason;
  useEffect(()=>{setHit(stored?.hitMilestone??false);setMainReason(stored?.mainErrorReason??commonError??'concept');setTop(stored?.nextWeekTop3??['','',''])},[weekStart,stored?.savedOn,commonError]);
 const scoresSorted=useMemo(()=>[...s.scores.filter(x=>x.date).sort((a,b)=>b.date!.localeCompare(a.date!)),...s.scores.filter(x=>!x.date)], [s.scores]);
 const submit=(e:React.FormEvent)=>{e.preventDefault();const amount=Number(obtained),outof=Number(total);if(!scoreLabel.trim()||outof<=0||amount<0||amount>outof)return;s.addScore({date:scoreDate,label:scoreLabel.trim(),subject:scoreSubject,...(scoreSubject==='english'?{paper:scorePaper}:{}),type:scoreType,obtained:amount,total:outof,note:note||undefined});setScoreLabel('');setObtained('');setNote('')};
 return <main className="mx-auto max-w-5xl space-y-5 px-4 pb-32 pt-6 sm:px-8"><header><p className="mono text-xs font-bold">LOOK BACK · RESET · GO AGAIN</p><h1 className="mt-2 text-5xl sm:text-6xl">Review.</h1></header>
  <nav className="grid grid-cols-2 gap-2" aria-label="Review sections">{([['weekly','WEEKLY'],['marks','MARKS']] as const).map(([id,label])=><button key={id} className={`brut-btn ${tab===id?'':'bg-white'}`} onClick={()=>setTab(id)} aria-pressed={tab===id} data-testid={`tab-review-${id}`}>{label}</button>)}</nav>
  {tab==='weekly'&&<><section className="brut p-4 sm:p-6"><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="mono text-xs font-bold">WEEK OF {formatDate(weekStart,{day:'numeric',month:'long'})}</p><h2 className="mt-2 text-3xl">Sunday reset.</h2></div><span className="mono border-2 border-black bg-[var(--due)] px-2 py-1 text-xs">TIMED TEST REMINDER</span></div><div className="mt-5 space-y-5"><div className="flex items-center gap-3"><button role="checkbox" aria-checked={hit} className="grid h-10 w-10 place-items-center border-[3px] border-black" style={{background:hit?'var(--done)':'white'}} onClick={()=>setHit(v=>!v)} data-testid="check-weekly-milestone">{hit?'✓':''}</button><p className="font-bold">Did I hit this week’s Maths and Physics milestone?</p></div><div><div className="flex flex-wrap items-center justify-between gap-2"><p className="font-bold">Which R1 / R2 / R3 did I miss?</p><Button variant="ghost" onClick={()=>setShowOverdue(v=>!v)} data-testid="button-show-overdue">{showOverdue?'HIDE OVERDUE':'SHOW OVERDUE'} <ArrowRight size={17}/></Button></div>{showOverdue&&<div className="mt-2 space-y-2">{due.length?due.map(x=><p className="brut-sm p-3" key={`${x.chapter.id}-${x.revision.pass}`}>{SUBJECTS[x.chapter.subject].label} · {x.chapter.name} · {x.revision.pass}</p>):<p className="brut-sm bg-[var(--biology)] p-3">No overdue revisions. Keep the queue clear.</p>}</div>}</div><Field label="Main error reason this week"><select value={mainReason} onChange={e=>setMainReason(e.target.value as ErrorReason)} data-testid="select-weekly-error-reason">{['concept','calculation','silly','time'].map(x=><option key={x} value={x}>{x.toUpperCase()}{commonError===x?' · MOST LOGGED':''}</option>)}</select></Field><div><p className="mb-2 font-bold">Next week’s top three.</p><div className="space-y-2">{top.map((x,i)=><Field label={`Item ${i+1}`} key={i}><input value={x} onChange={e=>setTop(prev=>prev.map((v,j)=>i===j?e.target.value:v) as [string,string,string])} placeholder={['Maths: one topic to finish','Physics: stay a chapter ahead','One revision pass to protect'][i]} data-testid={`input-next-week-${i+1}`}/></Field>)}</div></div><Button className="w-full" onClick={()=>s.saveReview({weekStart,hitMilestone:hit,mainErrorReason:mainReason,nextWeekTop3:top,savedOn:today})} data-testid="button-save-review">SAVE THIS WEEK’S REVIEW</Button></div></section>
  <section className="space-y-3"><h2 className="text-3xl">Past reviews.</h2>{s.reviews.filter(r=>r.weekStart!==weekStart).sort((a,b)=>b.weekStart.localeCompare(a.weekStart)).map(r=><article className="brut-sm p-4" key={r.weekStart} data-testid={`review-${r.weekStart}`}><div className="flex items-center justify-between gap-2"><h3 className="text-xl">Week of {formatDate(r.weekStart,{day:'numeric',month:'long'})}</h3><span className="mono text-xs">{r.hitMilestone?'MILESTONE HIT':'MILESTONE MISSED'}</span></div><p className="mt-2">Main error: {r.mainErrorReason??'not set'}</p><ol className="mt-2 list-inside list-decimal">{r.nextWeekTop3.filter(Boolean).map((item,i)=><li key={i}>{item}</li>)}</ol></article>)}</section></>}
  {tab==='marks'&&<><section className="brut p-4" style={{background:'var(--due)'}}><p className="mono text-xs font-bold">HALF-YEARLY · NOTES, NOT NUMBERS</p><div className="mt-3 grid gap-2 sm:grid-cols-2">{HALF_YEARLY_NOTES.map(n=><div className="border-2 border-black bg-white p-3" key={n.subject}><b>{n.subject}</b><p>{n.verdict}</p></div>)}</div><p className="display mt-4 text-lg">Cause: not revising properly. Fixing that is the whole plan.</p></section>
  <section><div className="flex items-baseline justify-between"><h2 className="text-3xl">Marks at a glance.</h2><span className="mono text-xs">GOAL · 100%</span></div><div className="mt-3 grid gap-3 sm:grid-cols-2">{primarySubjects.map(subject=>{const data=s.scores.filter(x=>x.subject===subject).sort((a,b)=>(b.date??'').localeCompare(a.date??'')),last=data[0],trend=subjectTrend(s.scores,subject),target=scoreTarget(subject,today);const Trend=trend==='up'?ArrowUp:trend==='down'?ArrowDown:ArrowRight;return <article key={subject} className="brut p-4" style={{background:subject==='maths'||subject==='physics'?SUBJECTS[subject].color:'white'}} data-testid={`score-card-${subject}`}><div className="flex items-start justify-between"><div><Tag subject={subject}/><p className="mono mt-3 text-xs">LATEST SCORE</p></div><Trend size={24} strokeWidth={3} aria-label={`Trend ${trend}`}/></div><div className="mt-2 flex items-end gap-2"><strong className="display text-5xl" data-testid={`value-score-${subject}`}>{last?`${pct(last)}%`:'—'}</strong><span className="mono mb-1 text-xs">{last?last.label:'No test logged'}</span></div><div className="mt-3 flex items-baseline justify-between"><span className="mono text-xs">TARGET {target}%</span><span className="mono text-xs">{data.length} SCORES</span></div><div className="mt-2 grid grid-cols-8 gap-1">{Array.from({length:8},(_,i)=>{const score=data[7-i];return <div key={i} className="h-5 border-2 border-black" title={score?`${score.label}: ${pct(score)}%`:'No score'} style={{background:score?(pct(score)>=target?'var(--done)':'var(--overdue)'):'white'}}/>})}</div></article>})}</div></section>
  <p className="brut-sm p-3 font-bold" data-testid="text-score-targets">Maths 70% until Nov 21, then 85%. Physics 75% then 85%. Others 85%.</p>
  <section className="brut p-4"><h2 className="text-3xl">Log a score.</h2><form className="mt-3 grid gap-3 sm:grid-cols-2" onSubmit={submit}><Field label="Date"><input type="date" value={scoreDate} onChange={e=>setScoreDate(e.target.value)} data-testid="input-score-date"/></Field><Field label="Subject"><select value={scoreSubject} onChange={e=>setScoreSubject(e.target.value as SubjectId)} data-testid="select-score-subject">{SUBJECT_ORDER.map(x=><option key={x} value={x}>{SUBJECTS[x].label}</option>)}</select></Field>{scoreSubject==='english'&&<Field label="English paper"><select value={scorePaper} onChange={e=>setScorePaper(e.target.value as typeof scorePaper)} data-testid="select-score-paper"><option value="language">English 1 · Language</option><option value="literature">English 2 · Literature</option></select></Field>}<Field label="Score type"><select value={scoreType} onChange={e=>setScoreType(e.target.value as ScoreType)} data-testid="select-score-type">{[['unit','Unit test'],['chapter-test','Chapter test'],['full-paper','Full paper'],['pyq-set','PYQ set'],['practical-mock','Practical mock'],['pre-board','Pre-board'],['half-yearly','Half-yearly']].map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></Field><Field label="Label"><input required value={scoreLabel} onChange={e=>setScoreLabel(e.target.value)} placeholder="e.g. Chapter test: Definite Integrals" data-testid="input-score-label"/></Field><div className="grid grid-cols-2 gap-2"><Field label="Marks"><input type="number" min="0" value={obtained} onChange={e=>setObtained(e.target.value)} required data-testid="input-score-obtained"/></Field><Field label="Out of"><input type="number" min="1" value={total} onChange={e=>setTotal(e.target.value)} required data-testid="input-score-total"/></Field></div><Field label="Note (optional)"><input value={note} onChange={e=>setNote(e.target.value)} data-testid="input-score-note"/></Field><div className="flex items-end"><Button className="w-full" type="submit" data-testid="button-add-score">SAVE SCORE</Button></div></form></section>
  <section className="space-y-3"><div className="flex items-baseline justify-between"><h2 className="text-3xl">Score history.</h2><span className="mono text-xs">{scoresSorted.length} TOTAL</span></div>{scoresSorted.map(score=><article className="brut-sm flex flex-wrap items-center gap-3 p-3" key={score.id} data-testid={`score-history-${score.id}`}><Tag subject={score.subject}/><div className="min-w-40 flex-1"><b>{score.label}</b><p className="mono text-xs">{score.date?formatDate(score.date,{day:'numeric',month:'short',year:'numeric'}):'Before half-yearly'} · {score.type.toUpperCase()}</p>{score.note&&<p className="mt-1 text-sm">{score.note}</p>}</div><strong className="mono text-xl">{score.obtained}/{score.total} · {pct(score)}%</strong><button className="brut-btn bg-white" onClick={()=>s.deleteScore(score.id)} aria-label={`Delete ${score.label}`} data-testid={`button-delete-score-${score.id}`}><Trash2 size={18} strokeWidth={3}/></button></article>)}</section></>}
 </main>
}