import {useRef,useState} from 'react';
import {ArrowLeft,Bell,CloudUpload,Download,FileUp,RotateCcw,Settings2} from 'lucide-react';
import {useNavigate} from 'react-router-dom';
import {Button,Field,Guess} from '../components/Brut';
import {SyncPanel} from '../components/SyncPanel';
import {SnapshotsPanel} from '../components/SnapshotsPanel';
import {NotifyPanel} from '../components/NotifyPanel';
import {downloadBackup} from '../backup';
import {markOverride} from '../sync';
import {useStore} from '../store';
import {formatDate} from '../dates';
import {derivePhases} from '../phases';
import {SUBJECT_ORDER,SUBJECTS} from '../seed';
import {DEFAULT_HARDNESS,IMPORTANCE,schoolHas} from '../priority';
import type {SubjectId} from '../types';
export function SettingsPage({openSetup}:{openSetup:()=>void}){
 const s=useStore(),navigate=useNavigate(),fileRef=useRef<HTMLInputElement>(null),[confirmReset,setConfirmReset]=useState(false),[message,setMessage]=useState('');
 const dateFields=[['practicals','Practicals'],['preBoards','Pre-boards'],['boards','Boards']] as const;
  const download=()=>{downloadBackup(s.exportAll());setMessage('Backup downloaded to your computer. Find it in Downloads and save a fresh copy after important changes.')};
 const importFile=async(file?:File)=>{if(!file)return;try{s.importAll(await file.text());markOverride();setMessage('Backup restored. Your tracker is up to date.')}catch{setMessage('That file isn’t a BLOCKS backup. Nothing changed.')}if(fileRef.current)fileRef.current.value=''};
  const phases=derivePhases(s.settings.examDates),hasDateGuesses=Object.values(s.settings.examDates.confirmed).some(confirmed=>!confirmed);
  const trackedNames=(subject:SubjectId)=>{const seen=new Set<string>(),out:string[]=[];for(const item of [...s.pending,...s.chapters]){if(item.subject!==subject)continue;const key=item.name.trim().toLowerCase();if(!key||seen.has(key))continue;seen.add(key);out.push(item.name)}return out};
 return <main className="mx-auto max-w-4xl space-y-5 px-4 pb-32 pt-6 sm:px-8"><header className="flex items-start gap-3"><button className="brut-btn bg-white" onClick={()=>navigate(-1)} aria-label="Go back" data-testid="button-back-settings"><ArrowLeft strokeWidth={3}/></button><div><p className="mono text-xs font-bold">APP CONTROLS</p><h1 className="mt-2 text-5xl sm:text-6xl">Settings.</h1></div></header>
  <section className="brut p-4"><div className="flex items-center gap-3"><Settings2 size={25} strokeWidth={3}/><h2 className="text-3xl">Exam dates.</h2></div><p className="mt-2">These dates set your timeline. A guess stays marked until school confirms it.</p><div className="mt-4 space-y-3">{dateFields.map(([key,label])=><article className="brut-sm grid gap-3 p-3 sm:grid-cols-[1fr_auto]" key={key} data-testid={`setting-date-${key}`}><Field label={label}><input type="date" value={s.settings.examDates[key]} onChange={e=>s.setExamDate(key,e.target.value,s.settings.examDates.confirmed[key])} data-testid={`input-date-${key}`}/></Field><label className="flex min-h-12 items-center gap-2 self-end"><input type="checkbox" className="h-6 w-6" checked={s.settings.examDates.confirmed[key]} onChange={e=>s.setExamDate(key,s.settings.examDates[key],e.target.checked)} data-testid={`check-date-confirmed-${key}`}/>{s.settings.examDates.confirmed[key]?<span className="mono border-2 border-black bg-[var(--done)] px-2 py-1">CONFIRMED</span>:<Guess/>}</label></article>)}</div><h3 className="mt-5 text-xl">Derived timeline.</h3><div className="mt-2 space-y-2">{phases.map(p=><p className="mono flex flex-wrap items-center gap-2 border-2 border-black bg-white p-3 text-sm" key={p.id}>PHASE {p.id} · {formatDate(p.start,{day:'numeric',month:'short',year:'numeric'})} → {formatDate(p.end,{day:'numeric',month:'short',year:'numeric'})}{hasDateGuesses&&<Guess/>}</p>)}</div></section>
  <section className="brut p-4"><h2 className="text-3xl">Priority engine.</h2><p className="mt-2">Every backlog chapter gets a priority score that decides when it gets scheduled and which core subject owns the peak-morning Block A slot.</p><p className="mono mt-3 border-2 border-black bg-white p-3 text-sm">P = [(B × H × I) + (D exam − D school)] × (1 − S)</p><p className="mt-2 text-sm">B is 1 until you learn the chapter (0 after). H is how hard you find the subject. I is how much it matters — PCMB core subjects count 1, English counts {IMPORTANCE.english}. The date gap is days until pre-boards minus days until school finishes the subject: a bigger gap pushes you to start sooner. S is 1 once school has finished a chapter, dropping it to priority zero.</p><div className="mt-4 space-y-3">{SUBJECT_ORDER.map(subject=><article className="brut-sm grid gap-3 p-3 sm:grid-cols-[1fr_auto] sm:items-end" key={subject} data-testid={`setting-hardness-${subject}`}><div><p className="font-bold">{SUBJECTS[subject].label}</p><p className="mono text-xs">H = HARDNESS · I = {IMPORTANCE[subject]}{IMPORTANCE[subject]===1?' · PCMB CORE':''}</p></div><Field label="H (0 to 2)"><input type="number" min={0} max={2} step={0.1} value={s.settings.hardness?.[subject]??DEFAULT_HARDNESS[subject]} onChange={e=>s.setHardness(subject,Number(e.target.value))} data-testid={`input-hardness-${subject}`}/></Field></article>)}</div></section>
   <section className="brut p-4"><h2 className="text-3xl">School sync.</h2><p className="mt-2">Mark what school has already finished. Finished chapters drop to priority zero and sink to the back of the pacer, so chapters school hasn’t touched stay at full priority and get self-studied ahead of the class. Set when school will wrap each subject to feed the pacing gap.</p><div className="mt-4 space-y-3">{SUBJECT_ORDER.map(subject=>{const names=trackedNames(subject),doneCount=names.filter(name=>schoolHas(s.schoolSync,subject,name)).length;return <article className="brut-sm p-3" key={subject} data-testid={`setting-school-${subject}`}><div className="flex flex-wrap items-center justify-between gap-3"><span className="mono border-2 border-black px-2 py-1 text-xs font-bold" style={{background:SUBJECTS[subject].color}}>{SUBJECTS[subject].label}</span><Field label="School finishes by"><input type="date" value={s.schoolSync.expected[subject]??''} onChange={e=>s.setSchoolExpected(subject,e.target.value)} data-testid={`input-school-expected-${subject}`}/></Field></div>{names.length?<details className="mt-3 border-2 border-black bg-white p-2"><summary className="mono cursor-pointer text-xs font-bold" data-testid={`summary-school-${subject}`}>SCHOOL-FINISHED CHAPTERS ({doneCount}/{names.length})</summary><div className="mt-2 space-y-1">{names.map((name,i)=>{const done=schoolHas(s.schoolSync,subject,name);return <label className="flex min-h-10 items-center gap-2 border-2 border-black p-2" key={name}><input className="h-5 w-5" type="checkbox" checked={done} onChange={()=>s.toggleSchoolDone(subject,name)} data-testid={`check-school-${subject}-${i}`}/><span className={done?'line-through':''}>{name}</span></label>})}</div></details>:<p className="mono mt-3 text-xs">NOTHING TRACKED YET — ADD CHAPTERS IN SETUP.</p>}</article>})}</div></section>
   <section className="brut p-4"><h2 className="text-3xl">Syllabus sequence.</h2><p className="mt-2">Your chapters, your order. Set a custom learning sequence per subject and the pacer rebuilds around it — Blocks A, B and C pull chapters in the exact order you define instead of the default priority guess.</p><Button className="mt-4" onClick={()=>navigate('/sequence')} data-testid="button-open-sequence">OPEN SEQUENCE EDITOR</Button></section>
   <section className="brut p-4"><h2 className="text-3xl">Projects &amp; submissions.</h2><p className="mt-2">Log internal deadlines — projects, assignments, practical write-ups — with a hand-in date and estimated hours. BLOCKS slices the work across the days left and, when a deadline is close, lifts it into Block A so it runs before anything else.</p><Button className="mt-4" onClick={()=>navigate('/submissions')} data-testid="button-open-submissions">OPEN SUBMISSIONS MANAGER</Button></section>
   <section className="brut p-4"><div className="flex items-center gap-3"><Bell size={25} strokeWidth={3}/><h2 className="text-3xl">Reminders.</h2></div><p className="mt-2">One notification a day, only when the day actually has something in it.</p><NotifyPanel/></section>
   <section className="brut p-4"><h2 className="text-3xl">Your data.</h2><p className="mt-2">Your tracker lives in this browser. Download a JSON backup so it survives a cleared browser, a new device or a broken update. Make a fresh backup after important changes.</p><div className="mt-4 grid gap-3 sm:grid-cols-2"><Button onClick={download} data-testid="button-export"><Download size={19} strokeWidth={3}/> SAVE BACKUP TO COMPUTER</Button><Button variant="ghost" onClick={()=>fileRef.current?.click()} data-testid="button-import"><FileUp size={19} strokeWidth={3}/> RESTORE FROM BACKUP</Button><input ref={fileRef} type="file" accept=".json,application/json" className="hidden" onChange={e=>void importFile(e.target.files?.[0])} data-testid="input-import-file"/></div>{message&&<p className="brut-sm mt-3 bg-[var(--biology)] p-3" role="status" data-testid="status-backup">{message}</p>}<SnapshotsPanel onRestore={json=>{try{s.importAll(json);markOverride();setMessage('Snapshot restored. Your tracker is back to that point and queued to sync.')}catch{setMessage('That snapshot could not be read. Nothing changed.')}}}/></section>
   <section className="brut p-4"><div className="flex items-center gap-3"><CloudUpload size={25} strokeWidth={3}/><h2 className="text-3xl">Sync &amp; devices.</h2></div><p className="mt-2">Keep one copy across your phone and computer. Turn sync on here, copy the private key, and paste it into this same settings screen on your other device. Both copies then stay identical, and a rolling history lets you roll back to any of the last 50 saved states.</p><SyncPanel/></section>
   <section className="brut p-4"><h2 className="text-3xl">Setup.</h2><p className="mt-2">Change the finished chapter list or update each unfinished topic’s start date, study estimate, and surplus. Existing chapters stay in the tracker.</p><Button className="mt-4" onClick={openSetup} data-testid="button-reopen-setup">RUN SETUP AGAIN</Button></section>
  <section className="brut border-[var(--overdue)] p-4"><h2 className="text-3xl">Start over.</h2><p className="mt-2">This removes chapters, scores, reviews and your settings from this device.</p>{!confirmReset?<Button variant="danger" className="mt-4" onClick={()=>setConfirmReset(true)} data-testid="button-reset">RESET ALL DATA</Button>:<div className="brut-sm mt-4 bg-[var(--overdue)] p-4 text-white" role="alertdialog" aria-label="Confirm reset"><p className="display text-xl">This can’t be undone.</p><p className="mt-2">Export a backup first if you might want this data later.</p><div className="mt-3 flex flex-wrap gap-2"><Button variant="ghost" onClick={()=>setConfirmReset(false)} data-testid="button-cancel-reset">KEEP MY DATA</Button><Button variant="danger" onClick={()=>{s.resetAll();markOverride();setConfirmReset(false);setMessage('Data cleared. The setup wizard is ready.');openSetup()}} data-testid="button-confirm-reset"><RotateCcw size={18}/> YES, RESET</Button></div></div>}</section>
 </main>
}