import {useRef,useState} from 'react';
import {ArrowLeft,Download,FileUp,RotateCcw,Settings2} from 'lucide-react';
import {useNavigate} from 'react-router-dom';
import {Button,Field,Guess} from '../components/Brut';
import {useStore} from '../store';
import {formatDate} from '../dates';
import {derivePhases} from '../phases';
export function SettingsPage({openSetup}:{openSetup:()=>void}){
 const s=useStore(),navigate=useNavigate(),fileRef=useRef<HTMLInputElement>(null),[confirmReset,setConfirmReset]=useState(false),[message,setMessage]=useState('');
 const dateFields=[['practicals','Practicals'],['preBoards','Pre-boards'],['boards','Boards']] as const;
  const download=()=>{const blob=new Blob([s.exportAll()],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`blocks-backup-${new Date().toLocaleDateString('en-CA')}.json`;document.body.appendChild(a);a.click();a.remove();window.setTimeout(()=>URL.revokeObjectURL(url),1000);setMessage('Backup downloaded to your computer. Find it in Downloads and save a fresh copy after important changes.')};
 const importFile=async(file?:File)=>{if(!file)return;try{s.importAll(await file.text());setMessage('Backup restored. Your tracker is up to date.')}catch{setMessage('That file isn’t a BLOCKS backup. Nothing changed.')}if(fileRef.current)fileRef.current.value=''};
 const phases=derivePhases(s.settings.examDates),hasDateGuesses=Object.values(s.settings.examDates.confirmed).some(confirmed=>!confirmed);
 return <main className="mx-auto max-w-4xl space-y-5 px-4 pb-32 pt-6 sm:px-8"><header className="flex items-start gap-3"><button className="brut-btn bg-white" onClick={()=>navigate(-1)} aria-label="Go back" data-testid="button-back-settings"><ArrowLeft strokeWidth={3}/></button><div><p className="mono text-xs font-bold">APP CONTROLS</p><h1 className="mt-2 text-5xl sm:text-6xl">Settings.</h1></div></header>
  <section className="brut p-4"><div className="flex items-center gap-3"><Settings2 size={25} strokeWidth={3}/><h2 className="text-3xl">Exam dates.</h2></div><p className="mt-2">These dates set your timeline. A guess stays marked until school confirms it.</p><div className="mt-4 space-y-3">{dateFields.map(([key,label])=><article className="brut-sm grid gap-3 p-3 sm:grid-cols-[1fr_auto]" key={key} data-testid={`setting-date-${key}`}><Field label={label}><input type="date" value={s.settings.examDates[key]} onChange={e=>s.setExamDate(key,e.target.value,s.settings.examDates.confirmed[key])} data-testid={`input-date-${key}`}/></Field><label className="flex min-h-12 items-center gap-2 self-end"><input type="checkbox" className="h-6 w-6" checked={s.settings.examDates.confirmed[key]} onChange={e=>s.setExamDate(key,s.settings.examDates[key],e.target.checked)} data-testid={`check-date-confirmed-${key}`}/>{s.settings.examDates.confirmed[key]?<span className="mono border-2 border-black bg-[var(--done)] px-2 py-1">CONFIRMED</span>:<Guess/>}</label></article>)}</div><h3 className="mt-5 text-xl">Derived timeline.</h3><div className="mt-2 space-y-2">{phases.map(p=><p className="mono flex flex-wrap items-center gap-2 border-2 border-black bg-white p-3 text-sm" key={p.id}>PHASE {p.id} · {formatDate(p.start,{day:'numeric',month:'short',year:'numeric'})} → {formatDate(p.end,{day:'numeric',month:'short',year:'numeric'})}{hasDateGuesses&&<Guess/>}</p>)}</div></section>
   <section className="brut p-4"><h2 className="text-3xl">Your data.</h2><p className="mt-2">Your tracker stays in this browser. Download a JSON backup to your computer so you can restore it if browser data is cleared. Make a fresh backup after important changes.</p><div className="mt-4 grid gap-3 sm:grid-cols-2"><Button onClick={download} data-testid="button-export"><Download size={19} strokeWidth={3}/> SAVE BACKUP TO COMPUTER</Button><Button variant="ghost" onClick={()=>fileRef.current?.click()} data-testid="button-import"><FileUp size={19} strokeWidth={3}/> RESTORE FROM BACKUP</Button><input ref={fileRef} type="file" accept=".json,application/json" className="hidden" onChange={e=>void importFile(e.target.files?.[0])} data-testid="input-import-file"/></div>{message&&<p className="brut-sm mt-3 bg-[var(--biology)] p-3" role="status" data-testid="status-backup">{message}</p>}</section>
   <section className="brut p-4"><h2 className="text-3xl">Setup.</h2><p className="mt-2">Change the finished chapter list or update each unfinished topic’s start date, study estimate, and surplus. Existing chapters stay in the tracker.</p><Button className="mt-4" onClick={openSetup} data-testid="button-reopen-setup">RUN SETUP AGAIN</Button></section>
  <section className="brut border-[var(--overdue)] p-4"><h2 className="text-3xl">Start over.</h2><p className="mt-2">This removes chapters, scores, reviews and your settings from this device.</p>{!confirmReset?<Button variant="danger" className="mt-4" onClick={()=>setConfirmReset(true)} data-testid="button-reset">RESET ALL DATA</Button>:<div className="brut-sm mt-4 bg-[var(--overdue)] p-4 text-white" role="alertdialog" aria-label="Confirm reset"><p className="display text-xl">This can’t be undone.</p><p className="mt-2">Export a backup first if you might want this data later.</p><div className="mt-3 flex flex-wrap gap-2"><Button variant="ghost" onClick={()=>setConfirmReset(false)} data-testid="button-cancel-reset">KEEP MY DATA</Button><Button variant="danger" onClick={()=>{s.resetAll();setConfirmReset(false);setMessage('Data cleared. The setup wizard is ready.');openSetup()}} data-testid="button-confirm-reset"><RotateCcw size={18}/> YES, RESET</Button></div></div>}</section>
 </main>
}