import {useMemo,useState} from 'react';
import {ArrowLeft,Trash2} from 'lucide-react';
import {useNavigate} from 'react-router-dom';
import {Button,Field,Tag} from '../components/Brut';
import {useStore} from '../store';
import {formatDate,todayISO} from '../dates';
import {SUBJECT_ORDER,SUBJECTS} from '../seed';
import {DAY_BUDGET_MIN,SLICE_CAP_MIN,URGENT_DAYS,dueLabel,planSubmissions,sliceLabel} from '../submissions';
import type {SubjectId} from '../types';

export function SubmissionsPage(){
 const s=useStore(),navigate=useNavigate(),today=todayISO();
 const [title,setTitle]=useState(''),[subject,setSubject]=useState<SubjectId>('maths'),[deadline,setDeadline]=useState(todayISO()),[hours,setHours]=useState('3'),[notes,setNotes]=useState('');
 const plans=useMemo(()=>planSubmissions(s.submissions,today),[s.submissions,today]);
 const done=useMemo(()=>s.submissions.filter(item=>item.doneOn).sort((a,b)=>(b.doneOn??'').localeCompare(a.doneOn??'')),[s.submissions]);
 const submit=(event:React.FormEvent)=>{event.preventDefault();const name=title.trim();if(!name||!deadline)return;const value=Number(hours);s.addSubmission({title:name,subject,deadline,hours:Number.isFinite(value)&&value>0?value:1,notes:notes.trim()||undefined});setTitle('');setNotes('')};
 return <main className="mx-auto max-w-5xl space-y-5 px-4 pb-32 pt-6 sm:px-8">
  <header className="flex items-start gap-3"><button className="brut-btn bg-white" onClick={()=>navigate(-1)} aria-label="Go back" data-testid="button-back-submissions"><ArrowLeft strokeWidth={3}/></button><div><p className="mono text-xs font-bold">DEADLINES / PROJECTS &amp; HOMEWORK</p><h1 className="mt-2 text-5xl sm:text-6xl">Submissions.</h1></div></header>
  <section className="brut-sm bg-[var(--biology)] p-4"><p className="font-bold">Log the deadline and how many hours it will take. BLOCKS slices that work across the days left and slots it into your blocks — it never steals a whole day from your backlog or revision queue.</p><ul className="mono mt-2 space-y-1 text-xs"><li>AT MOST {SLICE_CAP_MIN} MIN PER SUBMISSION PER DAY · {DAY_BUDGET_MIN} MIN PER DAY IN TOTAL.</li><li>ANYTHING DUE IN {URGENT_DAYS} DAYS OR FEWER BUBBLES INTO BLOCK A AND RUNS FIRST.</li><li>MARK IT SUBMITTED AND THE SLICE DISAPPEARS FROM YOUR ROUTINE.</li></ul></section>
  <section className="brut p-4"><h2 className="text-3xl">Add a submission.</h2><form onSubmit={submit} className="mt-3 grid gap-3 sm:grid-cols-2"><Field label="What is it?"><input required value={title} onChange={e=>setTitle(e.target.value)} placeholder="Maths project, Physics file, History PPT…" data-testid="input-submission-title"/></Field><Field label="Subject"><select value={subject} onChange={e=>setSubject(e.target.value as SubjectId)} data-testid="select-submission-subject">{SUBJECT_ORDER.map(x=><option value={x} key={x}>{SUBJECTS[x].label}</option>)}</select></Field><Field label="Hand it in on"><input required type="date" value={deadline} onChange={e=>setDeadline(e.target.value)} data-testid="input-submission-deadline"/></Field><Field label="Estimated hours"><input required type="number" min="0.5" step="0.5" value={hours} onChange={e=>setHours(e.target.value)} data-testid="input-submission-hours"/></Field><div className="sm:col-span-2"><Field label="Notes (optional)"><input value={notes} onChange={e=>setNotes(e.target.value)} placeholder="What it involves" data-testid="input-submission-notes"/></Field></div><div className="flex items-end"><Button type="submit" className="w-full" data-testid="button-add-submission">ADD SUBMISSION</Button></div></form></section>
  <section className="space-y-3"><div className="flex flex-wrap items-end justify-between gap-3"><h2 className="text-3xl">In your routine.</h2><span className="mono text-xs">{plans.length} ACTIVE · {plans.reduce((total,plan)=>total+plan.minutesToday,0)} MIN TODAY</span></div>
   {!plans.length?<div className="brut-sm bg-[var(--biology)] p-6" data-testid="empty-submissions"><h3 className="text-2xl">Nothing due.</h3><p>Add a project or assignment above and the pacer will start slicing it in.</p></div>:plans.map(plan=>{const item=plan.submission;return <article className="brut-sm flex flex-wrap items-center gap-3 p-3" key={item.id} data-testid={`submission-${item.id}`}><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><Tag subject={item.subject}/><span className="mono border-2 border-black px-2 py-1 text-xs font-bold" style={plan.overdue?{background:'var(--overdue)',color:'white'}:plan.urgent?{background:'var(--due)'}:{background:'white'}} data-testid={`submission-due-${item.id}`}>{dueLabel(plan)}</span>{plan.atRisk&&<span className="mono border-2 border-black px-2 py-1 text-xs font-bold" style={{background:'var(--overdue)',color:'white'}} data-testid={`submission-risk-${item.id}`}>NEEDS {plan.paceMin} MIN/DAY</span>}</div><p className="mt-2 font-bold">{item.title}</p><p className="mono mt-1 text-xs">HAND IN {formatDate(item.deadline,{weekday:'short',day:'numeric',month:'short'})} · {plan.totalMin} MIN TOTAL · {plan.paceMin} MIN/DAY TO STAY ON TRACK</p>{item.notes&&<p className="mt-1 text-sm">{item.notes}</p>}<p className="mono mt-2 inline-block border-2 border-black bg-[var(--biology)] px-2 py-1 text-xs font-bold" data-testid={`submission-slice-${item.id}`}>{sliceLabel(plan)}</p></div><Button onClick={()=>s.completeSubmission(item.id)} data-testid={`button-complete-submission-${item.id}`}>SUBMITTED</Button><Button variant="danger" onClick={()=>{if(window.confirm(`Delete ${item.title}?`))s.deleteSubmission(item.id)}} data-testid={`button-delete-submission-${item.id}`}><Trash2 size={18}/> DELETE</Button></article>})}
  </section>
  {!!done.length&&<section className="space-y-3"><h2 className="text-3xl">Submitted.</h2>{done.map(item=><article className="brut-sm flex flex-wrap items-center gap-3 p-3" key={item.id} data-testid={`submission-done-${item.id}`}><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><Tag subject={item.subject}/><span className="mono border-2 border-black bg-[var(--done)] px-2 py-1 text-xs font-bold">DONE</span></div><p className="mt-2 font-bold">{item.title}</p><p className="mono mt-1 text-xs">HAND IN {formatDate(item.deadline,{day:'numeric',month:'short'})} · SUBMITTED {item.doneOn?formatDate(item.doneOn):''}</p></div><Button variant="ghost" onClick={()=>s.reopenSubmission(item.id)} data-testid={`button-reopen-submission-${item.id}`}>REOPEN</Button><Button variant="danger" onClick={()=>{if(window.confirm(`Delete ${item.title}?`))s.deleteSubmission(item.id)}} data-testid={`button-delete-submission-history-${item.id}`}><Trash2 size={18}/> DELETE</Button></article>)}</section>}
 </main>;
}
