import {useEffect,useState} from 'react';
import {AlarmClock,ArrowRight,CalendarClock,Clock,Flame} from 'lucide-react';
import {Button,CheckBox,Guess,Tag} from '../components/Brut';
import {useStore} from '../store';
import {addDays,daysBetween,formatDate,getDueItems,missedYesterday,todayISO} from '../dates';
import {APP_START,currentPhase,derivePhases} from '../phases';
import {BLOCK_TIMES,SUBJECTS,WEEK_TEMPLATE} from '../seed';
import {behindFlags} from '../flags';
import type {BlockId,SubjectId} from '../types';
import type {BlockPlan} from '../seed';
type Props={startFocus:(minutes:number)=>void;settings:()=>void};
export function TodayPage({startFocus,settings}:Props){
 const state=useStore(),today=todayISO(),log=state.days[today],phase=currentPhase(state.settings.examDates,today),due=getDueItems(state.chapters,today),missed=missedYesterday(state.days,today,APP_START);
 const minimumRevision=due[0]??state.chapters.flatMap(chapter=>chapter.revisions.filter(revision=>!revision.doneOn).map(revision=>({chapter,revision}))).sort((a,b)=>a.revision.dueOn.localeCompare(b.revision.dueOn))[0];
 const [showAll,setShowAll]=useState(false),setMinimum=state.setMinimumDay;
  useEffect(()=>{if(missed&&!log)setMinimum(today,true)},[missed,today,log,setMinimum]);
 const currentPlan=WEEK_TEMPLATE[new Date().getDay()];
 const papers=state.papers;const first=papers[0],last=papers.at(-1);
 const paperMode=!!first&&!!last&&today>=addDays(first.date,-2)&&today<=last.date;
 const nextPaper=papers.find(p=>p.date>=today);
 const blocks:Record<BlockId,BlockPlan>=paperMode&&nextPaper
  ?{A:{subject:nextPaper.subject,focus:nextPaper.subject==='maths'?'Formulas + your error log':`Revise only for ${SUBJECTS[nextPaper.subject].label}`},B:{subject:nextPaper.subject,focus:'Past paper questions + key definitions'},C:{subject:nextPaper.subject,focus:'Light recall. Pack what you need.'}}
  :currentPlan;
 const flags=behindFlags({pending:state.pending,scores:state.scores,days:state.days,chapters:state.chapters,today});
 const todaySessions=state.sessions.filter(session=>session.date===today);
 const exams=state.settings.examDates;
 const countdowns=[['Practicals',exams.practicals,'var(--biology)','practicals'],['Pre-boards',exams.preBoards,'var(--due)','preBoards'],['Boards',exams.boards,'var(--english)','boards']] as const;
 const p2=derivePhases(exams)[2],practicalToday=today>=p2.start&&today<=p2.end;
 const visible=showAll?due:due.slice(0,3);
 return <main className="mx-auto max-w-5xl space-y-5 px-4 pb-32 pt-5 sm:px-8 sm:pt-8">
  <header className="flex flex-wrap items-end justify-between gap-3">
   <div><p className="mono text-sm font-bold">{formatDate(today,{weekday:'long',day:'numeric',month:'long',year:'numeric'})}</p><h1 className="mt-2 text-5xl sm:text-6xl">Today.</h1>{phase&&<span className="mono mt-3 inline-block border-[3px] border-black bg-[var(--due)] px-3 py-2 text-xs font-bold" data-testid="text-current-phase">PHASE {phase.id}: {phase.name.toUpperCase()}</span>}</div>
   <div className="mono flex items-center gap-2 border-[3px] border-black bg-white p-2 text-sm" data-testid="text-focus-minutes"><Clock size={18} strokeWidth={3}/>{log?.focusMinutes??0} MIN LOGGED</div>
  </header>
  {!!todaySessions.length&&<div className="brut-sm flex flex-wrap items-center gap-2 bg-white p-3" data-testid="list-today-sessions"><span className="mono text-xs font-bold">TODAY’S SESSIONS</span>{todaySessions.slice(0,3).map(session=><span key={session.id} className="mono border-2 border-black px-2 py-1 text-xs" style={{background:SUBJECTS[session.subject].color}}>{session.minutes}m {SUBJECTS[session.subject].label} · {session.method}</span>)}</div>}
  <section className="grid grid-cols-3 gap-2 sm:gap-4" aria-label="Exam countdowns">
   {countdowns.map(([label,date,color,key])=><div key={key} className="brut-sm min-w-0 p-2 sm:p-4" style={{background:color}} data-testid={`countdown-${key}`}><div className="flex min-h-6 items-center justify-between gap-1"><span className="mono truncate text-[10px] font-bold uppercase sm:text-xs">{label}</span>{!exams.confirmed[key]&&<Guess/>}</div><div className="display mono mt-2 text-4xl leading-none sm:text-6xl">{Math.max(daysBetween(today,date),0)}</div><p className="mono mt-2 text-[10px] sm:text-xs">{formatDate(date,{day:'numeric',month:'short'})}</p></div>)}
  </section>
  {!Object.values(exams.confirmed).every(Boolean)&&<div className="brut-sm flex flex-wrap items-center justify-between gap-3 bg-[var(--due)] p-4" data-testid="banner-exam-guesses"><p className="font-bold">Exam dates are guesses. Confirm them when school tells you.</p><Button variant="ghost" onClick={settings} data-testid="button-confirm-dates">EDIT DATES <ArrowRight size={18} strokeWidth={3}/></Button></div>}
  {paperMode&&nextPaper&&<section className="brut p-5" style={{background:SUBJECTS[nextPaper.subject].color}} data-testid="panel-next-paper"><div className="mono text-xs font-bold">PRE-BOARD MODE / NEXT PAPER</div><h2 className="mt-3 text-4xl sm:text-5xl">{SUBJECTS[nextPaper.subject].label}{nextPaper.paper?` · ${nextPaper.paper}`:''}</h2><p className="mono mt-2 text-lg">{formatDate(nextPaper.date,{weekday:'long',day:'numeric',month:'long'})} · {daysBetween(today,nextPaper.date)===0?'TODAY':daysBetween(today,nextPaper.date)===1?'TOMORROW':`IN ${daysBetween(today,nextPaper.date)} DAYS`}</p><p className="mt-3 font-bold">Between papers, revise only the next paper. Sleep before 10.</p></section>}
  {missed&&<div className="brut-sm flex items-start gap-3 bg-[var(--due)] p-4" data-testid="banner-missed-yesterday"><Flame size={23} strokeWidth={3}/><p className="font-bold">Missed yesterday. Fine. Don’t miss twice. Minimum Day only.</p></div>}
  {flags.length>0&&<section aria-label="Behind schedule" className="space-y-2">{flags.slice(0,3).map(flag=><div key={flag.id} className="brut-sm flex flex-wrap items-baseline gap-3 p-3" style={{background:flag.severity==='red'?'var(--overdue)':'var(--due)',color:flag.severity==='red'?'white':'var(--ink)'}} data-testid={`flag-${flag.id}`}><span className="display text-lg">{flag.severity==='red'?'BEHIND':'HEADS UP'}</span><p className="font-bold">{flag.text}</p></div>)}</section>}
  {log?.minimumDay&&<div className="brut-sm flex flex-wrap items-center justify-between gap-3 bg-[var(--biology)] p-3"><div><strong className="display text-lg">Minimum Day</strong><p>Maths 45 min + 1 revision. That’s a win.</p></div><button role="switch" aria-checked="true" className="brut-btn bg-white" onClick={()=>setMinimum(today,false)} data-testid="switch-minimum-day">ON · TURN OFF</button></div>}
  {!log?.minimumDay&&<button role="switch" aria-checked="false" className="brut-sm flex min-h-12 w-full items-center justify-between p-3 text-left" onClick={()=>setMinimum(today,true)} data-testid="switch-minimum-day"><span className="font-bold">Switch to Minimum Day</span><span className="mono border-2 border-black bg-white px-3 py-1">OFF</span></button>}
   {log?.minimumDay?<section className="grid gap-3 sm:grid-cols-2"><article className={`brut flex items-center gap-4 p-4 ${log?.minimumDone.maths?'is-done':''}`}><CheckBox checked={!!log?.minimumDone.maths} onClick={()=>state.toggleMinimum(today,'maths')} label="Minimum day Maths done" testId="check-minimum-maths"/><div className="flex-1"><Tag subject="maths"/><p className="display mt-2 text-xl">Maths · 45 min</p></div></article><article className={`brut flex items-center gap-4 p-4 ${log?.minimumDone.revision?'is-done':''}`}><CheckBox checked={!!log?.minimumDone.revision} onClick={()=>{if(!log?.minimumDone.revision&&minimumRevision)state.completeRevision(minimumRevision.chapter.id,minimumRevision.revision.pass);state.toggleMinimum(today,'revision')}} label="Minimum day revision done" testId="check-minimum-revision"/><div className="flex-1"><p className="mono text-xs font-bold">ONE REVISION</p><p className="mt-2 font-bold">{minimumRevision?.chapter.name??'Pick one chapter and review it.'}{minimumRevision?` · ${minimumRevision.revision.pass}`:''}</p></div></article></section>
   :<section className="space-y-3"><div className="flex items-baseline justify-between"><h2 className="text-3xl">Three blocks.</h2><span className="mono text-xs">FLEXIBLE, NOT FIXED</span></div>{(['A','B','C'] as const).map((block:BlockId)=>{const plan=blocks[block],sub=plan.subject in SUBJECTS?plan.subject as SubjectId:undefined;const color=sub?SUBJECTS[sub].color:plan.subject==='test'?'var(--ink)':plan.subject==='flex'?'var(--due)':'white';const done=!!log?.blocksDone[block];return <article className={`brut p-4 ${done?'is-done':''}`} key={block} data-testid={`card-block-${block}`}><div className="flex items-start gap-3"><span className="display grid h-12 w-12 shrink-0 place-items-center border-[3px] border-black text-2xl" style={{background:color,color:plan.subject==='test'?'white':'var(--ink)'}}>{block}</span><div className="min-w-0 flex-1">{sub?<Tag subject={sub}/>:<span className="mono border-2 border-black bg-white px-2 py-1 text-xs font-bold">{String(plan.subject).toUpperCase()}</span>}<p className="mt-2 text-lg font-bold leading-tight">{plan.focus}</p><p className="mono mt-1 text-xs text-[var(--muted)]">{BLOCK_TIMES[block].length} · {BLOCK_TIMES[block].weekday}</p></div><CheckBox checked={done} onClick={()=>state.toggleBlock(today,block)} label={`Block ${block} done`} testId={`check-block-${block}`}/></div>{!done&&<Button className="mt-3 w-full" onClick={()=>startFocus(25)} data-testid={`button-start-block-${block}`}>START BLOCK {block}</Button>}{done&&<p className="mt-3 font-bold">Block done. Nice.</p>}</article>})}</section>}
  {practicalToday&&<div className={`brut-sm flex flex-wrap items-center gap-3 p-4 ${log?.practicalDone?'is-done':''}`} data-testid="daily-practical"><CheckBox checked={!!log?.practicalDone} onClick={()=>state.togglePracticalToday(today)} label="Practical 30 minutes done" testId="check-daily-practical"/><div className="flex-1"><p className="display">Practical: 30 min today</p><p>Small run-through counts.</p></div><Button variant="ghost" onClick={()=>startFocus(25)} data-testid="button-start-practical">START</Button></div>}
  <section className="brut p-4 sm:p-5"><div className="flex flex-wrap items-baseline justify-between gap-2"><div><p className="mono text-xs font-bold">SPACED REVISION</p><h2 className="mt-1 text-3xl">Due today <span className="mono text-xl">({due.length})</span></h2></div>{due.length>0&&<p className="mono text-xs">OVERDUE FIRST · R1 FIRST</p>}</div>{due.length===0?<div className="mt-4 border-[3px] border-black bg-[var(--biology)] p-4"><p className="display text-xl">Nothing due. Go get ahead.</p></div>:<div className="mt-4 space-y-2">{visible.map(({chapter,revision,status})=><div className="brut-sm flex items-center gap-3 p-3" key={`${chapter.id}-${revision.pass}`} data-testid={`revision-${chapter.id}-${revision.pass}`}><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><Tag subject={chapter.subject}/><span className={`mono border-2 border-black px-2 py-1 text-xs font-bold ${status==='overdue'?'bg-[var(--overdue)] text-white':'bg-[var(--due)]'}`}>{status.toUpperCase()}</span><span className="mono text-xs">{revision.pass}</span></div><p className="mt-2 font-bold">{chapter.name}</p></div><CheckBox checked={false} onClick={()=>state.completeRevision(chapter.id,revision.pass)} label={`${revision.pass} complete: ${chapter.name}`} testId={`check-revision-${chapter.id}-${revision.pass}`}/></div>)}</div>}{due.length>3&&<button className="mt-3 min-h-12 border-b-[3px] border-black font-bold" onClick={()=>setShowAll(v=>!v)} data-testid="button-show-all-revisions">{showAll?'SHOW LESS':`SHOW ALL (${due.length})`}</button>}</section>
  {!!state.pending.filter(p=>!p.doneOn).length&&<section className="brut p-4"><div className="flex items-center justify-between gap-2"><h2 className="text-2xl">Still to learn.</h2><CalendarClock strokeWidth={3}/></div><div className="mt-3 space-y-2">{state.pending.filter(p=>!p.doneOn).map(p=><article key={p.id} className="brut-sm flex flex-wrap items-center gap-3 p-3" data-testid={`pending-${p.id}`}><div className="min-w-0 flex-1"><Tag subject={p.subject}/><p className="mt-2 font-bold">{p.name}</p><p className="mono mt-1 text-xs">DUE {formatDate(p.due,{day:'numeric',month:'short'})}</p></div><Button onClick={()=>state.markPendingLearned(p.id)} data-testid={`button-learned-${p.id}`}>LEARNED TODAY</Button></article>)}</div></section>}
  <Button className="w-full py-5 text-xl" onClick={()=>startFocus(10)} data-testid="button-start-10"><AlarmClock size={22} strokeWidth={3}/> START 10 MIN</Button>
 </main>
}